CREATE TABLE FOO (
FOO_ID INTEGER NOT NULL
,FOO_VALUE VARCHAR(30)
)
;

ALTER TABLE FOO ADD CONSTRAINT PK_FOO PRIMARY KEY (FOO_ID)
;
INSERT INTO FOO (FOO_ID, FOO_VALUE) VALUES (233, 'This is added by siva')
;
